package app

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/danielhanold/docket/internal/assets"
	"github.com/danielhanold/docket/internal/domain"
	"github.com/danielhanold/docket/internal/gitcli"
	"github.com/danielhanold/docket/internal/testsupport"
	"github.com/danielhanold/docket/internal/workspace"
)

func TestPathsGeneratedOnly(t *testing.T) {
	cases := []struct {
		name  string
		paths []string
		want  bool
	}{
		{"manifest only", []string{"internal/assets/embedded/manifest.json"}, true},
		{"tree paths", []string{"internal/assets/embedded/tree/skills/x/SKILL.md", "internal/assets/embedded/manifest.json"}, true},
		{"mixed authored", []string{"internal/assets/embedded/manifest.json", "skills/x/SKILL.md"}, false},
		{"authored only", []string{"feature.txt"}, false},
		{"empty set", nil, false},
		{"bundle dir itself is not an output path", []string{"internal/assets/embedded"}, false},
		{"lookalike sibling", []string{"internal/assets/embedded-other/manifest.json"}, false},
	}
	for _, c := range cases {
		if got := pathsGeneratedOnly(c.paths); got != c.want {
			t.Errorf("%s: pathsGeneratedOnly(%v) = %v, want %v", c.name, c.paths, got, c.want)
		}
	}
}

// writeBundleFixtureRepo lays down a minimal eligible workspace: go.mod with the
// Docket module identity, all four DefaultAllowedRoots, and a committed-shape
// embedded bundle generated by the real generator. Returns the dir.
func writeBundleFixtureRepo(t *testing.T, module string) string {
	t.Helper()
	dir := testsupport.TempDir(t)
	writeFileT(t, dir, "go.mod", "module "+module+"\n\ngo 1.22\n")
	writeFileT(t, dir, "skills/demo/SKILL.md", "demo skill v1\n")
	writeFileT(t, dir, "agents/demo.md", "demo agent\n")
	writeFileT(t, dir, "cursor-rules/demo.mdc", "demo rule\n")
	writeFileT(t, dir, ".docket.example.yml", "version: 1\n")
	m, payload, err := assets.Generate(dir, assets.DefaultAllowedRoots())
	if err != nil {
		t.Fatalf("generate fixture bundle: %v", err)
	}
	if err := assets.WriteTree(filepath.Join(dir, "internal", "assets", "embedded"), m, payload); err != nil {
		t.Fatalf("write fixture bundle: %v", err)
	}
	return dir
}

func writeFileT(t *testing.T, dir, rel, content string) {
	t.Helper()
	full := filepath.Join(dir, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestBundleRepoEligible(t *testing.T) {
	eligible := writeBundleFixtureRepo(t, docketModulePath)
	if !bundleRepoEligible(eligible) {
		t.Fatalf("a Docket-module workspace with all roots and a committed bundle must be eligible")
	}
	foreign := writeBundleFixtureRepo(t, "github.com/someone/else")
	if bundleRepoEligible(foreign) {
		t.Fatalf("a foreign module identity must never be eligible")
	}
	noBundle := testsupport.TempDir(t)
	writeFileT(t, noBundle, "go.mod", "module "+docketModulePath+"\n")
	if bundleRepoEligible(noBundle) {
		t.Fatalf("a workspace without the committed bundle and roots must not be eligible")
	}
	noGoMod := writeBundleFixtureRepo(t, docketModulePath)
	if err := os.Remove(filepath.Join(noGoMod, "go.mod")); err != nil {
		t.Fatal(err)
	}
	if bundleRepoEligible(noGoMod) {
		t.Fatalf("an unreadable module identity must not be eligible (probe error is not clean absence)")
	}
}

func TestRegenerateEmbeddedBundle(t *testing.T) {
	dir := writeBundleFixtureRepo(t, docketModulePath)
	// Drift the authored root: add one file, delete another's bundle copy, and
	// corrupt the manifest the way a conflicted stop leaves it.
	writeFileT(t, dir, "skills/demo/SKILL.md", "demo skill v2\n")
	writeFileT(t, dir, "skills/extra/SKILL.md", "brand new skill\n")
	writeFileT(t, dir, "internal/assets/embedded/manifest.json", "<<<<<<< conflict markers\n")
	writeFileT(t, dir, "internal/assets/embedded/tree/skills/stale/SKILL.md", "stale payload the regen must delete\n")

	if err := regenerateEmbeddedBundle(dir); err != nil {
		t.Fatalf("regenerate: %v", err)
	}
	m, payload, err := assets.Generate(dir, assets.DefaultAllowedRoots())
	if err != nil {
		t.Fatalf("re-generate for diff: %v", err)
	}
	diffs, err := assets.DiffTree(filepath.Join(dir, "internal", "assets", "embedded"), m, payload)
	if err != nil {
		t.Fatalf("diff: %v", err)
	}
	if len(diffs) != 0 {
		t.Fatalf("the regenerated bundle drifts from the authored roots: %v", diffs)
	}
	if _, err := os.Stat(filepath.Join(dir, "internal/assets/embedded/tree/skills/stale/SKILL.md")); !os.IsNotExist(err) {
		t.Fatalf("regeneration did not delete the stale payload file (err=%v)", err)
	}
}

// --- advanceGeneratedOnly non-advancing-stop guard (unit) -----------------

// fakeGenWorkspace is the minimal FinalizeWorkspace advanceGeneratedOnly touches:
// AcquireOperationLock and ReadRebaseReceipt. Every other method is inherited
// from the nil embedded interface, so ANY other call (a receipt WRITE in
// particular) panics — which is exactly how this unit proves the non-advancing
// stop spends no resolver state: advanceGeneratedOnly reads the receipt but never
// writes it, so a nil-pointer panic would fire if the guard path tried to.
type fakeGenWorkspace struct {
	FinalizeWorkspace
	rec     workspace.RebaseReceipt
	present bool
}

func (w *fakeGenWorkspace) AcquireOperationLock(string) (func(), error) {
	return func() {}, nil
}

func (w *fakeGenWorkspace) ReadRebaseReceipt(context.Context, string) (workspace.RebaseReceipt, bool, error) {
	return w.rec, w.present, nil
}

// fakeGenContinueGit scripts the two continue-Git probes the fast-path loop
// drives: StoppedRebaseCommit always returns the SAME object id (a stop that
// never advances), and StageAndContinueRebase always returns a still-conflicted,
// bundle-only status (so the loop would re-enter forever without the guard). A
// call cap on StageAndContinueRebase turns the non-terminating mutation into a
// deterministic, fast red instead of a hang: with the `stopped == prev` guard
// present the second iteration returns errBundleNotAdvancing before staging a
// second time (stage runs exactly once), so the cap is never reached.
type fakeGenContinueGit struct {
	FinalizeContinueGit
	stopped    gitcli.ObjectID
	next       gitcli.RebaseStatus
	stageCalls int
}

func (g *fakeGenContinueGit) StoppedRebaseCommit(context.Context, string) (gitcli.ObjectID, error) {
	return g.stopped, nil
}

func (g *fakeGenContinueGit) StageAndContinueRebase(context.Context, string, []string) (gitcli.RebaseStatus, error) {
	g.stageCalls++
	if g.stageCalls > 3 {
		return gitcli.RebaseStatus{}, fmt.Errorf(
			"loop did not terminate: StageAndContinueRebase called %d times on a non-advancing stop", g.stageCalls)
	}
	return g.next, nil
}

// TestAdvanceGeneratedOnlyNonAdvancingStopBlocks pins advanceGeneratedOnly's
// infinite-loop-termination guard: a fast-path continue that leaves the rebase
// stopped on the SAME commit (regeneration could not clear it) must block
// through the existing failure path rather than loop. It reddens when the
// `stopped == prev` branch is stripped (the loop no longer terminates; the
// StageAndContinueRebase call cap fires and the refusal message loses the
// errBundleNotAdvancing text this asserts).
func TestAdvanceGeneratedOnlyNonAdvancingStopBlocks(t *testing.T) {
	ctx := context.Background()
	wsDir := writeBundleFixtureRepo(t, docketModulePath) // eligible Docket workspace

	bundleOnly := gitcli.RebaseStatus{
		Disposition:   gitcli.RebaseConflicted,
		UnmergedPaths: []string{embeddedBundleDir + "/manifest.json"},
	}
	git := &fakeGenContinueGit{
		stopped: gitcli.ObjectID(strings.Repeat("a", 40)), // same id every call: never advances
		next:    bundleOnly,                               // continue re-surfaces the same bundle-only stop
	}
	deps := FinalizeDeps{
		// A present receipt with no outstanding reservation and no started
		// continuation lets the fast path proceed past the step-aside check.
		Workspace:   &fakeGenWorkspace{present: true},
		ContinueGit: git,
		// A no-op regeneration so the unit exercises only the loop's advance guard,
		// never the real generator.
		RegenerateBundle: func(string) error { return nil },
	}
	rc := &rebaseContext{
		change:  domain.NewChange(domain.ChangeSpec{ID: 413}),
		wsDir:   wsDir,
		metaDir: filepath.Join(wsDir, ".meta"),
	}

	status, refusal := advanceGeneratedOnly(ctx, deps, OperationFinalizeRebase, rc, bundleOnly)
	if refusal == nil {
		t.Fatalf("a non-advancing bundle-only stop returned no refusal (status %+v)", status)
	}
	if refusal.Result != ResultBlocked || refusal.Reason != ReasonRebaseGitFailed {
		t.Fatalf("refusal = (%q, %q), want (%q, %q)", refusal.Result, refusal.Reason, ResultBlocked, ReasonRebaseGitFailed)
	}
	if !strings.Contains(refusal.Message, errBundleNotAdvancing.Error()) {
		t.Fatalf("refusal message = %q, want it to carry the errBundleNotAdvancing text %q", refusal.Message, errBundleNotAdvancing.Error())
	}
	// The guard returns on the SECOND iteration, so the continue staged exactly
	// once — it never loops on the unchanged stop.
	if git.stageCalls != 1 {
		t.Fatalf("StageAndContinueRebase call count = %d, want exactly 1 (guard must stop the loop after one non-advancing continue)", git.stageCalls)
	}
}

// --- advanceGeneratedOnly reservation/continuation step-aside guard (unit) ---

// stepAsideContinueGit fails the test if any rebase-Git mutation is attempted.
// The step-aside guard returns before the fast path ever reaches continueGit, so
// a passing test sees ZERO StageAndContinueRebase calls; if the guard is
// neutralized the loop runs, StageAndContinueRebase is called, and the non-zero
// count reddens the assertion. StoppedRebaseCommit returns a non-zero id and
// StageAndContinueRebase returns a non-conflicted status so a mutated loop
// terminates deterministically (a fast red, never a hang).
type stepAsideContinueGit struct {
	FinalizeContinueGit
	stageCalls int
}

func (g *stepAsideContinueGit) StoppedRebaseCommit(context.Context, string) (gitcli.ObjectID, error) {
	return gitcli.ObjectID(strings.Repeat("b", 40)), nil
}

func (g *stepAsideContinueGit) StageAndContinueRebase(context.Context, string, []string) (gitcli.RebaseStatus, error) {
	g.stageCalls++
	return gitcli.RebaseStatus{}, nil // non-conflicted: lets a mutated loop terminate
}

// TestAdvanceGeneratedOnlyStepsAsideForOwnedResolver pins the concurrency-safety
// guard: when the resolver flow already owns the stop — an outstanding
// reservation token, or a started continuation — the fast path must fall through
// to the normal resolver flow (return status, nil) WITHOUT mutating Git, so it
// never regenerates or continues the rebase out from under the owned reservation.
// The test proves "no Git action" three ways: a RegenerateBundle seam that fails
// the test if invoked, a ContinueGit seam that fails if StageAndContinueRebase is
// invoked, and an explicit zero-call assertion. It reddens when the step-aside
// condition is neutralized (the fast path then regenerates and stages).
func TestAdvanceGeneratedOnlyStepsAsideForOwnedResolver(t *testing.T) {
	ctx := context.Background()
	bundleOnly := gitcli.RebaseStatus{
		Disposition:   gitcli.RebaseConflicted,
		UnmergedPaths: []string{embeddedBundleDir + "/manifest.json"},
	}
	cases := []struct {
		name string
		rec  workspace.RebaseReceipt
	}{
		{
			name: "outstanding reservation token",
			rec: workspace.RebaseReceipt{
				ResolverReservationToken:   "tok-owned",
				ResolverReservationStopped: strings.Repeat("c", 40),
			},
		},
		{
			name: "continuation started",
			rec:  workspace.RebaseReceipt{ResolverContinuationStarted: "1"},
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			wsDir := writeBundleFixtureRepo(t, docketModulePath) // eligible Docket workspace
			git := &stepAsideContinueGit{}
			deps := FinalizeDeps{
				Workspace:   &fakeGenWorkspace{rec: c.rec, present: true},
				ContinueGit: git,
				RegenerateBundle: func(string) error {
					t.Fatalf("fast path regenerated the bundle while the resolver flow owned the stop")
					return nil
				},
			}
			rc := &rebaseContext{
				change:  domain.NewChange(domain.ChangeSpec{ID: 413}),
				wsDir:   wsDir,
				metaDir: filepath.Join(wsDir, ".meta"),
			}

			status, refusal := advanceGeneratedOnly(ctx, deps, OperationFinalizeRebase, rc, bundleOnly)
			if refusal != nil {
				t.Fatalf("step-aside must return no refusal, got %+v", *refusal)
			}
			if status.Disposition != bundleOnly.Disposition || len(status.UnmergedPaths) != len(bundleOnly.UnmergedPaths) {
				t.Fatalf("status changed: got %+v, want the input status %+v unchanged", status, bundleOnly)
			}
			if git.stageCalls != 0 {
				t.Fatalf("StageAndContinueRebase call count = %d, want 0 (fast path must take no Git action when the resolver flow owns the stop)", git.stageCalls)
			}
		})
	}
}

func TestRegenerateEmbeddedBundleFailsOnBrokenRoots(t *testing.T) {
	dir := writeBundleFixtureRepo(t, docketModulePath)
	if err := os.RemoveAll(filepath.Join(dir, "skills")); err != nil {
		t.Fatal(err)
	}
	if err := regenerateEmbeddedBundle(dir); err == nil {
		t.Fatalf("regeneration over a missing allowed root must fail, not write a partial bundle")
	}
	// The failure must leave the previous committed bundle in place (staging+rename,
	// never an in-place truncate).
	if _, err := os.Stat(filepath.Join(dir, "internal/assets/embedded/manifest.json")); err != nil {
		t.Fatalf("a failed regeneration destroyed the previous bundle: %v", err)
	}
}
