package app

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/danielhanold/docket/internal/assets"
)

func TestPathsGeneratedOnly(t *testing.T) {
	cases := []struct {
		name  string
		paths []string
		want  bool
	}{
		{"manifest only", []string{"internal/assets/embedded/manifest.json"}, true},
		{"tree paths", []string{"internal/assets/embedded/tree/skills/x/SKILL.md", "internal/assets/embedded/manifest.json"}, true},
		{"mixed authored", []string{"internal/assets/embedded/manifest.json", "skills/x/SKILL.md"}, false},
		{"authored only", []string{"feature.txt"}, false},
		{"empty set", nil, false},
		{"bundle dir itself is not an output path", []string{"internal/assets/embedded"}, false},
		{"lookalike sibling", []string{"internal/assets/embedded-other/manifest.json"}, false},
	}
	for _, c := range cases {
		if got := pathsGeneratedOnly(c.paths); got != c.want {
			t.Errorf("%s: pathsGeneratedOnly(%v) = %v, want %v", c.name, c.paths, got, c.want)
		}
	}
}

// writeBundleFixtureRepo lays down a minimal eligible workspace: go.mod with the
// Docket module identity, all four DefaultAllowedRoots, and a committed-shape
// embedded bundle generated by the real generator. Returns the dir.
func writeBundleFixtureRepo(t *testing.T, module string) string {
	t.Helper()
	dir := t.TempDir()
	writeFileT(t, dir, "go.mod", "module "+module+"\n\ngo 1.22\n")
	writeFileT(t, dir, "skills/demo/SKILL.md", "demo skill v1\n")
	writeFileT(t, dir, "agents/demo.md", "demo agent\n")
	writeFileT(t, dir, "cursor-rules/demo.mdc", "demo rule\n")
	writeFileT(t, dir, ".docket.example.yml", "version: 1\n")
	m, payload, err := assets.Generate(dir, assets.DefaultAllowedRoots())
	if err != nil {
		t.Fatalf("generate fixture bundle: %v", err)
	}
	if err := assets.WriteTree(filepath.Join(dir, "internal", "assets", "embedded"), m, payload); err != nil {
		t.Fatalf("write fixture bundle: %v", err)
	}
	return dir
}

func writeFileT(t *testing.T, dir, rel, content string) {
	t.Helper()
	full := filepath.Join(dir, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestBundleRepoEligible(t *testing.T) {
	eligible := writeBundleFixtureRepo(t, docketModulePath)
	if !bundleRepoEligible(eligible) {
		t.Fatalf("a Docket-module workspace with all roots and a committed bundle must be eligible")
	}
	foreign := writeBundleFixtureRepo(t, "github.com/someone/else")
	if bundleRepoEligible(foreign) {
		t.Fatalf("a foreign module identity must never be eligible")
	}
	noBundle := t.TempDir()
	writeFileT(t, noBundle, "go.mod", "module "+docketModulePath+"\n")
	if bundleRepoEligible(noBundle) {
		t.Fatalf("a workspace without the committed bundle and roots must not be eligible")
	}
	noGoMod := writeBundleFixtureRepo(t, docketModulePath)
	if err := os.Remove(filepath.Join(noGoMod, "go.mod")); err != nil {
		t.Fatal(err)
	}
	if bundleRepoEligible(noGoMod) {
		t.Fatalf("an unreadable module identity must not be eligible (probe error is not clean absence)")
	}
}

func TestRegenerateEmbeddedBundle(t *testing.T) {
	dir := writeBundleFixtureRepo(t, docketModulePath)
	// Drift the authored root: add one file, delete another's bundle copy, and
	// corrupt the manifest the way a conflicted stop leaves it.
	writeFileT(t, dir, "skills/demo/SKILL.md", "demo skill v2\n")
	writeFileT(t, dir, "skills/extra/SKILL.md", "brand new skill\n")
	writeFileT(t, dir, "internal/assets/embedded/manifest.json", "<<<<<<< conflict markers\n")
	writeFileT(t, dir, "internal/assets/embedded/tree/skills/stale/SKILL.md", "stale payload the regen must delete\n")

	if err := regenerateEmbeddedBundle(dir); err != nil {
		t.Fatalf("regenerate: %v", err)
	}
	m, payload, err := assets.Generate(dir, assets.DefaultAllowedRoots())
	if err != nil {
		t.Fatalf("re-generate for diff: %v", err)
	}
	diffs, err := assets.DiffTree(filepath.Join(dir, "internal", "assets", "embedded"), m, payload)
	if err != nil {
		t.Fatalf("diff: %v", err)
	}
	if len(diffs) != 0 {
		t.Fatalf("the regenerated bundle drifts from the authored roots: %v", diffs)
	}
	if _, err := os.Stat(filepath.Join(dir, "internal/assets/embedded/tree/skills/stale/SKILL.md")); !os.IsNotExist(err) {
		t.Fatalf("regeneration did not delete the stale payload file (err=%v)", err)
	}
}

func TestRegenerateEmbeddedBundleFailsOnBrokenRoots(t *testing.T) {
	dir := writeBundleFixtureRepo(t, docketModulePath)
	if err := os.RemoveAll(filepath.Join(dir, "skills")); err != nil {
		t.Fatal(err)
	}
	if err := regenerateEmbeddedBundle(dir); err == nil {
		t.Fatalf("regeneration over a missing allowed root must fail, not write a partial bundle")
	}
	// The failure must leave the previous committed bundle in place (staging+rename,
	// never an in-place truncate).
	if _, err := os.Stat(filepath.Join(dir, "internal/assets/embedded/manifest.json")); err != nil {
		t.Fatalf("a failed regeneration destroyed the previous bundle: %v", err)
	}
}
