#!/usr/bin/env bash
# scripts/render-learnings-index.sh — deterministic, idempotent renderer for the learnings index
# (<changes_dir>/learnings/README.md), change 0067. The exact analog of render-adr-index.sh (0030)
# and render-board.sh (0022): reads the finding files and emits the index to STDOUT byte-for-byte.
# No git writes (the caller redirects + commits), offline (no gh, no git, no network). Same finding
# files => identical bytes. Reuses lib/docket-frontmatter.sh.
#
# PURE BY DESIGN: this script has no learnings.enabled awareness. The CALLERS gate on it — exactly
# as render-board.sh stays pure while board-refresh.sh/docket-status.sh own the write decision.
#
# Usage: render-learnings-index.sh --learnings-dir DIR
set -uo pipefail

LEARNINGS_DIR=""
while [ $# -gt 0 ]; do
  case "$1" in
    --learnings-dir) LEARNINGS_DIR="$2"; shift ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) printf 'render-learnings-index: unknown argument: %s\n' "$1" >&2; exit 2 ;;
  esac
  shift
done
[ -n "$LEARNINGS_DIR" ] || { printf 'render-learnings-index: missing --learnings-dir\n' >&2; exit 2; }
[ -d "$LEARNINGS_DIR" ] || { printf 'render-learnings-index: learnings dir not found: %s\n' "$LEARNINGS_DIR" >&2; exit 2; }

# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/lib/docket-frontmatter.sh"

# `field` returns the RAW scalar — quotes intact. `hook` is REQUIRED to be quoted (it carries a
# colon-space; YAML-scalar family), so it must be dequoted here or the index ships quote bytes.
dequote(){ local v="$1"; v="${v#\"}"; v="${v%\"}"; v="${v#\'}"; v="${v%\'}"; printf '%s' "$v"; }

declare -A F_HOOK F_TOPICS F_STATE F_TO
SLUGS=""
mapfile -t FILES < <(find "$LEARNINGS_DIR" -maxdepth 1 -name '*.md' ! -name 'README.md' 2>/dev/null | sort)
for f in "${FILES[@]}"; do
  slug="$(field "$f" slug)"; [ -n "$slug" ] || continue
  F_HOOK["$slug"]="$(dequote "$(field "$f" hook)")"
  F_TOPICS["$slug"]="$(list_field "$f" topics)"
  state="$(field "$f" promotion_state)"
  # Positive off-state (ADR-0032): an unset/unknown state is NOT silently "retained" for the
  # purposes of the hint surface — it renders as retained, but only `promoted` leaves the groups
  # and only `candidate` earns the marker, so an empty value degrades to the safe, visible tier.
  F_STATE["$slug"]="${state:-retained}"
  F_TO["$slug"]="$(field "$f" promoted_to)"
  SLUGS+="$slug"$'\n'
done

primary_topic(){ # primary_topic SLUG -> first tag, or "uncategorized"
  local t; t="$(printf '%s' "${F_TOPICS[$1]}" | awk '{print $1}')"
  printf '%s' "${t:-uncategorized}"
}
rest_topics(){ # rest_topics SLUG -> "b, c" (empty when only one tag)
  printf '%s' "${F_TOPICS[$1]}" | awk '{ for(i=2;i<=NF;i++){ printf "%s%s", (i>2 ? ", " : ""), $i } }'
}

# --- partition: promoted findings leave the paid surface for the appendix -------------------
ACTIVE=""; PROMOTED=""
while IFS= read -r s; do
  [ -n "$s" ] || continue
  if [ "${F_STATE[$s]}" = "promoted" ]; then PROMOTED+="$s"$'\n'; else ACTIVE+="$s"$'\n'; fi
done <<<"$SLUGS"

# --- topic buckets (derived, sorted — no hand-listed topic set) -----------------------------
TOPICS_SEEN=""
while IFS= read -r s; do
  [ -n "$s" ] || continue
  TOPICS_SEEN+="$(primary_topic "$s")"$'\n'
done <<<"$ACTIVE"
TOPICS_SORTED="$(printf '%s' "$TOPICS_SEEN" | sed '/^$/d' | sort -u)"

row(){ # row SLUG
  local s="$1" line rest marker=""
  [ "${F_STATE[$s]}" = "candidate" ] && marker=" ⟨needs promotion⟩"
  line="- [$s]($s.md) — ${F_HOOK[$s]}"
  rest="$(rest_topics "$s")"
  [ -n "$rest" ] && line+=" · also: $rest"
  printf '%s%s\n' "$line" "$marker"
}

printf '# Learnings — the build loop'"'"'s memory\n\n'
printf 'One curated finding per file; this index is the hint surface. Load it, then read only the findings that bear on the change at hand. Generated by `render-learnings-index.sh` — do not hand-edit. Contract: docket-convention, "Learnings ledger".\n'

if [ -n "$TOPICS_SORTED" ]; then
  while IFS= read -r topic; do
    [ -n "$topic" ] || continue
    printf '\n## %s\n\n' "$topic"
    while IFS= read -r s; do
      [ -n "$s" ] || continue
      [ "$(primary_topic "$s")" = "$topic" ] && row "$s"
    done <<<"$(printf '%s' "$ACTIVE" | sed '/^$/d' | sort)"
  done <<<"$TOPICS_SORTED"
fi

PROMOTED_SORTED="$(printf '%s' "$PROMOTED" | sed '/^$/d' | sort)"
if [ -n "$PROMOTED_SORTED" ]; then
  printf '\n## Promoted\n\n'
  printf 'Graduated to an always-in-context agent-instructions file. Kept as the rule'"'"'s receipt, the harvest'"'"'s dedup memory, and a one-line-reversible demotion path — they no longer count against the cap.\n\n'
  while IFS= read -r s; do
    [ -n "$s" ] || continue
    printf -- '- [%s](%s.md) → %s\n' "$s" "$s" "${F_TO[$s]}"
  done <<<"$PROMOTED_SORTED"
fi
